# ==============================================================================
# Project: FinlandSports V2.0 - Fig 6 Clinical Composite Networks & Spatiotemporal GSEA
# Description: 
#   1. Global Alignment: Lean group hierarchical clustering anchors the Y-axis.
#   2. Visual Fixes: Markdown angle overlaps fixed, dual-borders removed, X-axis nested via '\n'.
#   3. Dual Output: Automatically generates both 'Comprehensive' and 'Curated' versions.
#   4. V2.0 Engine: Pure CSV reading, fixed duplicate column crash, strict namespacing.
# ==============================================================================

# --- 0. ENVIRONMENT SETUP ---
# setwd("C:/Users/Sorcier_W/Desktop/ATM/Exercise-Multiomics-Trios")

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  readr, dplyr, ggplot2, reshape2, patchwork, stringr, 
  scales, ggsci, grid, ggpubr, tidyr, ppcor, ggtext, openxlsx,
  clusterProfiler, msigdbr, enrichplot
)

# --- 1. GLOBAL CONFIGURATION ---
DIR_IN <- "01_Clean_Data"
DIR_OUT_ROOT <- "03_Results/Fig_6/Fig6_Clinical_Indices"
DIR_COMP <- file.path(DIR_OUT_ROOT, "Comprehensive_All_Targets")
DIR_CURA <- file.path(DIR_OUT_ROOT, "Curated_Selected_Targets")

dir.create(DIR_COMP, recursive = TRUE, showWarnings = FALSE)
dir.create(DIR_CURA, recursive = TRUE, showWarnings = FALSE)

# Raw Column Names Mapping to Target Keys
TARGET_DICT <- list(
  "HOMA_IR" = "HOMA-IR",
  "CRP"     = "hsCRP",
  "tOC"     = "tOC",
  "cOC"     = "cOC",
  "Ratio"   = "cOC/tOC Ratio"
)

COL_FAT  <- "#F79647"  
COL_LEAN <- "#3DA6AE" 
CLINICAL_COLORS <- c(
  "Bone Metabolism" = "#3C5488",            
  "Ectopic Adiposity" = "#E64B35",          
  "Body Composition" = "#F39B7F",           
  "Glucose & Lipids" = "#4DBBD5",           
  "Inflammation & Endocrine" = "#8491B4",   
  "Fitness & Lifestyle" = "#00A087",        
  "Other Traits" = "#7E6148"                
)

m1_comp_excel <- list()
m1_cura_excel <- list()
m3_excel_list <- list()

# --- 2. V2.0 CLINICAL DATA LOADER & RENAMING ENGINE ---
message("\n>>> Loading and Cleaning Clinical Dataset (V2.0 Engine)...")

df_clin <- read_csv(file.path(DIR_IN, "Clinical_Master_Strict.csv"), show_col_types = FALSE) %>%
  dplyr::mutate(
    Role_Orig = dplyr::case_when(Membercode == 1 ~ "Daughter", Membercode == 2 ~ "Mother", Membercode == 3 ~ "Father", TRUE ~ "Unknown"),
    Sample_Key = tolower(paste0(FamilyID, "_", Role_Orig))
  )

if("Age" %in% colnames(df_clin)) df_clin$Age <- as.numeric(df_clin$Age)
if("Gender" %in% colnames(df_clin)) df_clin$Gender <- as.numeric(as.factor(df_clin$Gender))
if("Fat(%)" %in% colnames(df_clin)) {
  df_clin$Fat_percent <- as.numeric(df_clin$`Fat(%)`)
  df_clin$Fat_Group <- ifelse(df_clin$Fat_percent >= 30, "Obese", "Lean")
}

protect_cols <- c("FamilyID", "Membercode", "Unique_Key", "Age", "Gender", "Fat_Group", "Sample_Key")
noise_blacklist <- c("SelfRatedHealthScore", "Health_History_Score", "Family_History_Score")
df_clin <- df_clin %>% dplyr::select(-dplyr::any_of(noise_blacklist))

rename_idx <- !colnames(df_clin) %in% protect_cols
new_names <- colnames(df_clin)[rename_idx]

new_names <- gsub("\\.E\\.\\.", "(E%)", new_names) 
new_names <- gsub("\\.E\\.$", "(E%)", new_names)   

rename_dict <- c(
  "^WAISTLINE$" = "WC",             "^Liverfat$" = "HFC",          "^liverfat$" = "HFC",
  "^A\\.L\\.Ratio$" = "A/L Ratio",  "^Fat_percent$" = "Fat(%)",    "^Energy_kcal$" = "IEE",
  "^IPA$" = "IPA",                  "^CRP$" = "hsCRP",             "^ALT$" = "S-ALAT",
  "^Testosterone$" = "Te",          "^Estradiol$" = "E2",          "^IGF1$" = "IGF-1",
  "^S_cOC$" = "cOC",                "^S_TotalOC$" = "tOC",         "^cOC_totalOC_ratio$" = "cOC/tOC Ratio",
  "^HOMA_IR$" = "HOMA-IR",          "^HandGrapeStrength$" = "HGS", "^ElbowFlex$" = "EFS",
  "^KneeExtention$" = "NES",        "^JumpHeight$" = "VJH",        "^PA_Hour\\.Week$" = "PAD",
  "^PA_Times\\.Week$" = "PAF",      "^VISCERAL$" = "Fat Vi",       "^Visceral$" = "Fat Vi",
  "^Visceralfat$" = "Fat Vi",       "^Vertebralfat$" = "Fat Ve",   "^SubcutaneousFat$" = "Fat Su",
  "^IntraperitonealFat$" = "Fat Ip", "^RetroperitonealFat$" = "Fat Rp", "^Muscle_totalfat$" = "Fat Mu",
  "^Android_FM$" = "FM An",         "^Android\\(FM\\)$" = "FM An", "^Gynoid_FM$" = "FM Gy",
  "^Gynoid\\(FM\\)$" = "FM Gy"
)

for(pattern in names(rename_dict)) {
  new_names <- stringr::str_replace_all(new_names, pattern, rename_dict[pattern])
}
colnames(df_clin)[rename_idx] <- new_names

# ==============================================================================
# [CORE FIX]: Remove duplicate columns generated by dictionary mapping
# ==============================================================================
df_clin <- df_clin[, !duplicated(colnames(df_clin))]
# ==============================================================================

# --- 3. V2.0 OMICS DATA LOADER (Base & Delta) ---
message(">>> Loading Omics Datasets for GSEA...")

get_omics_base_delta_v2 <- function(filename) {
  fpath <- file.path(DIR_IN, filename); if(!file.exists(fpath)) return(NULL)
  raw <- read_csv(fpath, show_col_types = FALSE)
  feat_ids <- raw[[1]]; expr_raw <- as.matrix(raw[, -1])
  
  clean_cols <- tolower(str_remove(colnames(expr_raw), "_twin\\.\\d+$")) %>% str_trim()
  col_meta <- data.frame(Matrix_Col = colnames(expr_raw), Clean_Col = clean_cols, stringsAsFactors = FALSE) %>%
    dplyr::mutate(
      TimePoint = dplyr::case_when(grepl("pre", Clean_Col) ~ "Pre", grepl("fast", Clean_Col) ~ "Pre", grepl("post3h", Clean_Col) ~ "Post3H", TRUE ~ "Other"),
      Subject_ID = gsub("_fast|_pre|_post1h|_post3h", "", Clean_Col)
    )
  
  df_wide <- col_meta %>% dplyr::filter(TimePoint %in% c("Pre", "Post3H")) %>%
    dplyr::group_by(Subject_ID, TimePoint) %>% dplyr::slice(1) %>% dplyr::ungroup()
  
  res_base <- data.frame(Subject_ID = unique(df_wide$Subject_ID)); res_delta <- data.frame(Subject_ID = unique(df_wide$Subject_ID))
  
  for(m in 1:nrow(expr_raw)) {
    gene <- feat_ids[m]
    v_pre <- expr_raw[m, df_wide$Matrix_Col[df_wide$TimePoint == "Pre"]]
    names(v_pre) <- df_wide$Subject_ID[df_wide$TimePoint == "Pre"]
    v_post <- expr_raw[m, df_wide$Matrix_Col[df_wide$TimePoint == "Post3H"]]
    names(v_post) <- df_wide$Subject_ID[df_wide$TimePoint == "Post3H"]
    
    res_base[[gene]] <- v_pre[res_base$Subject_ID]
    
    delta_vec <- c()
    for(s in res_delta$Subject_ID) {
      if(!is.na(v_pre[s]) && !is.na(v_post[s])) {
        if(v_pre[s] > 50) delta_vec <- c(delta_vec, log2(v_post[s]+1) - log2(v_pre[s]+1))
        else delta_vec <- c(delta_vec, v_post[s] - v_pre[s])
      } else { delta_vec <- c(delta_vec, NA) }
    }
    res_delta[[gene]] <- delta_vec
  }
  return(list(Base = res_base, Delta = res_delta))
}

DATA_MUSCLE <- get_omics_base_delta_v2("Cleaned_Muscle_Proteomics.csv")
DATA_FAT    <- get_omics_base_delta_v2("Cleaned_Adipose_Proteomics.csv")

# --- 4. MASTER LOOP FOR ALL METRICS ---
CURATED_FEATURES_DICT <- list(
  "HOMA_IR" = c("IGF-1", "tOC", "hsCRP", "Leptin", "A/L Ratio", "HFC", "AST", "S-ALAT", "CHOL", "LDL", "Fat Ve", "FM An"),
  "CRP"     = c("cOC/tOC Ratio", "cOC", "GGT", "HFC", "S-ALAT", "AST", "Leptin", "SHBG", "A/L Ratio", "Fat(%)", "Fat Vi", "FM An"),
  "tOC"     = c("TRACP5b", "ALP", "LDL", "CHOL", "TRIGLY", "WC", "Fat Vi", "FM Gy", "Te", "IGF-1", "HOMA-IR"),
  "cOC"     = c("TRACP5b", "ALP", "HFC", "AST", "S-ALAT", "LDL", "CHOL", "HOMA-IR", "VO2max", "IEE", "REE", "hsCRP"),
  "Ratio"   = c("hsCRP", "Leptin", "HFC", "AST", "S-ALAT", "GGT", "LDL", "TRIGLY", "Fat Ip", "FM An", "TRACP5b", "HOMA-IR")
)

assign_clinical_group <- function(var_names) {
  dplyr::case_when(
    var_names %in% c("TRACP5a", "TRACP5b", "ALP", "cOC", "tOC", "cOC/tOC Ratio") ~ "Bone Metabolism",
    var_names %in% c("Fat Vi", "Fat Ve", "HFC", "A/L Ratio", "Fat Ip", "Fat Rp") ~ "Ectopic Adiposity",
    var_names %in% c("Fat(%)", "FM An", "FM Gy", "Fat Su", "BMI", "WC") ~ "Body Composition",
    var_names %in% c("Insulin", "Glucose", "ISI", "HOMA-IR", "CHOL", "LDL", "HDL", "TRIGLY", "NEFA") ~ "Glucose & Lipids",
    var_names %in% c("hsCRP", "WBC", "Leptin", "AST", "S-ALAT", "GGT", "Adiponectin", "SHBG", "Te", "E2", "IGF-1") ~ "Inflammation & Endocrine",
    var_names %in% c("NES", "HGS", "VJH", "EFS", "VO2max", "PAD", "PAF", "IPA", "REE", "AEE", "IEE", "Fat Mu") ~ "Fitness & Lifestyle",
    TRUE ~ "Other Traits"
  )
}

for (index_name in names(TARGET_DICT)) {
  target_col <- TARGET_DICT[[index_name]]
  
  cat("\n=================================================================\n")
  cat(sprintf("▶ RUNNING PIPELINE FOR: %s (Column: %s)\n", index_name, target_col))
  cat("=================================================================\n")
  
  # Fail-safe skip if target column is not completely valid
  if(!target_col %in% colnames(df_clin)) {
    message("   [Skip] Target column not found: ", target_col)
    next
  }
  
  df_clin_target <- df_clin %>% dplyr::select(Sample_Key, TargetVal = dplyr::all_of(target_col)) %>% 
    dplyr::mutate(TargetVal = as.numeric(TargetVal)) %>% na.omit()
  
  if(nrow(df_clin_target) == 0) next
  
  # -------------------------------------------------------------------------
  # [MODULE 1] Clinical Correlation Scan
  # -------------------------------------------------------------------------
  message(">>> [MODULE 1] Executing Clinical Composites...")
  local({
    base_blacklist <- c("Age", "Gender", "Sex", "AGE", "group", "Group", "Height", "Weight", "height", "weight", 
                        "BMI_new", "Total_FM", "Total_LM", "Time", "choline", "CHESTCIRC_cm", 
                        "Fat Rp", "Fat Ip", "Total_BM", "Glyu", "Fat_Group", "Sample_Key", target_col)
    
    dynamic_blacklist <- base_blacklist
    if (index_name == "HOMA_IR") dynamic_blacklist <- c(dynamic_blacklist, "Insulin", "Glucose", "ISI")
    else if (index_name %in% c("tOC", "cOC", "Ratio")) dynamic_blacklist <- c(dynamic_blacklist, "tOC", "cOC", "cOC/tOC Ratio")
    else if (index_name == "CRP") dynamic_blacklist <- c(dynamic_blacklist, "WBC") 
    
    candidates <- setdiff(colnames(df_clin)[sapply(df_clin, is.numeric)], dynamic_blacklist)
    candidates <- candidates[!grepl("Family|Member|^ID$", candidates, ignore.case = TRUE)]
    
    calc_partial <- function(df_sub) {
      res_list <- list()
      for(col in candidates) {
        tmp <- df_sub %>% dplyr::select(dplyr::all_of(c(target_col, col, "Age", "Gender"))) %>% na.omit()
        if (nrow(tmp) > 10 && sd(tmp[[col]]) > 0 && sd(tmp[[target_col]]) > 0) {
          try({
            ct <- if(length(unique(tmp$Gender)) > 1) {
              ppcor::pcor.test(tmp[[col]], tmp[[target_col]], tmp[, c("Age", "Gender")], method = "spearman")
            } else {
              ppcor::pcor.test(tmp[[col]], tmp[[target_col]], tmp[, c("Age")], method = "spearman")
            }
            res_list[[col]] <- data.frame(Variable = col, Cor = ct$estimate, P_Value = ct$p.value)
          }, silent=TRUE)
        }
      }
      dplyr::bind_rows(res_list)
    }
    
    stats_obese <- calc_partial(df_clin %>% dplyr::filter(Fat_Group == "Obese"))
    stats_lean <- calc_partial(df_clin %>% dplyr::filter(Fat_Group == "Lean"))
    
    sig_obese <- stats_obese %>% dplyr::filter(P_Value < 0.05)
    sig_lean <- stats_lean %>% dplyr::filter(P_Value < 0.05)
    
    # 1. Comprehensive Generation (Top 25)
    target_vars_comp <- union(sig_obese$Variable, sig_lean$Variable)
    if(length(target_vars_comp) > 25) {
      target_vars_comp <- stats_lean %>% dplyr::filter(Variable %in% target_vars_comp) %>% dplyr::arrange(P_Value) %>% head(25) %>% dplyr::pull(Variable)
    }
    
    # 2. Curated Generation (Intersection with Dictionary)
    target_vars_cura <- c()
    if (index_name %in% names(CURATED_FEATURES_DICT)) {
      target_vars_cura <- intersect(CURATED_FEATURES_DICT[[index_name]], union(sig_obese$Variable, sig_lean$Variable))
    }
    
    # --- Shared Plotting Engine ---
    add_stars <- function(df) df %>% dplyr::mutate(Stars = dplyr::case_when(P_Value < 0.001 ~ "***", P_Value < 0.01 ~ "**", P_Value < 0.05 ~ "*", TRUE ~ ""))
    b_style <- element_rect(color = "black", fill = NA, linewidth = 1)
    
    draw_bar <- function(df, title, is_obese, max_abs) {
      ggplot(df, aes(x = Variable, y = Cor)) +
        geom_segment(aes(x=Variable, xend=Variable, y=0, yend=Cor), color="grey60", linewidth=1.2) +
        geom_point(aes(fill = Group, size = abs(Cor)), shape = 21, color = "white", stroke=0.8) +
        geom_text(aes(label = Stars, y = Cor, hjust=ifelse(Cor>=0, -2, 2)), vjust=0.75, size=11, color="black") +
        scale_fill_manual(name = "Clinical Category", values = CLINICAL_COLORS, drop = TRUE) + 
        scale_size(range = c(5, 11), guide = "none") +
        geom_hline(yintercept = 0, linetype="dashed", color="black") +
        scale_y_continuous(limits = c(-max_abs, max_abs), expand = expansion(mult = c(0.45, 0.45))) + coord_flip() +
        labs(title = title, y = expression("Partial "*rho), x="") + 
        theme_minimal(base_size = 14) + 
        theme(
          aspect.ratio = 1, panel.border = b_style, axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.line = element_blank(), 
          panel.grid = element_blank(), plot.title = element_text(face="bold", hjust=0.5, size=15, color="black"), 
          axis.text.x = element_text(color="black", size=15), axis.title.x = element_text(color="black", size=14, face="bold")
        )
    }
    
    draw_heat <- function(vars_ordered, grp, title, is_obese) {
      sub_df <- df_clin %>% dplyr::filter(Fat_Group == grp) %>% dplyr::select(dplyr::all_of(as.character(vars_ordered)))
      c_mat <- cor(sub_df, use="pairwise.complete.obs", method="spearman")
      melted <- melt(c_mat)
      melted$Var1 <- factor(melted$Var1, levels = as.character(vars_ordered))
      melted$Var2 <- factor(melted$Var2, levels = as.character(vars_ordered))
      
      ggplot(melted, aes(Var1, Var2, fill = value)) + 
        geom_tile(color="black", linewidth=0.5) +
        scale_fill_gradient2(low="#3C5488", mid="white", high="#DC0000", midpoint=0, limits=c(-1,1), name=expression("Partial "*rho), guide = guide_colorbar(direction = "horizontal", title.position = "left", title.vjust = 0.5, barwidth = unit(5, "cm"))) +
        labs(title=title) + theme_minimal(base_size=14) +
        theme(
          aspect.ratio = 1, plot.title = element_text(face="bold", hjust=0.5, size=15, color="black"),
          axis.text.x = ggtext::element_markdown(angle=45, hjust=1, vjust=1, color="black", size=15), 
          axis.text.y = ggtext::element_markdown(color="black", size=14),
          axis.title = element_blank(), panel.grid=element_blank()
        ) 
    }
    
    generate_m1_panel <- function(vars_list, out_dir, prefix) {
      if(length(vars_list) < 3) return(NULL)
      
      # Anchor ordering to Lean clustering
      sub_df_lean <- df_clin %>% dplyr::filter(Fat_Group == "Lean") %>% dplyr::select(dplyr::all_of(vars_list))
      c_mat_lean <- cor(sub_df_lean, use="pairwise.complete.obs", method="spearman")
      hc_lean <- hclust(as.dist(1 - c_mat_lean))
      g_order <- vars_list[hc_lean$order]
      
      plot_obese <- stats_obese %>% dplyr::filter(Variable %in% vars_list) %>% dplyr::mutate(Group = assign_clinical_group(Variable))
      plot_lean <- stats_lean %>% dplyr::filter(Variable %in% vars_list) %>% dplyr::mutate(Group = assign_clinical_group(Variable))
      
      plot_obese$Variable <- factor(plot_obese$Variable, levels = g_order)
      plot_lean$Variable <- factor(plot_lean$Variable, levels = g_order)
      
      plot_obese <- add_stars(plot_obese); plot_lean <- add_stars(plot_lean)
      max_abs <- max(abs(c(plot_obese$Cor, plot_lean$Cor)), na.rm=T) * 1.1
      
      p_heat_obese <- draw_heat(g_order, "Obese", "Collinearity Matrix (Obese)", TRUE)
      p_bar_obese <- draw_bar(plot_obese, paste("Associations with", index_name, "(Obese)"), TRUE, max_abs)
      p_heat_lean <- draw_heat(g_order, "Lean", "Collinearity Matrix (Lean)", FALSE)
      p_bar_lean <- draw_bar(plot_lean, paste("Associations with", index_name, "(Lean)"), FALSE, max_abs)
      
      p_heat_lean <- p_heat_lean + guides(fill = "none") 
      p_bar_lean <- p_bar_lean + guides(fill = "none")
      
      p_final <- (p_heat_lean | p_bar_lean | p_heat_obese | p_bar_obese) + 
        plot_layout(guides = "collect") &
        theme(legend.position = "bottom", legend.box = "horizontal", legend.title = element_text(size = 14, face = "bold"), legend.text = element_text(size = 13), legend.margin = margin(t = 0, b = 0)) &
        guides(fill = guide_legend(nrow = 1, override.aes = list(size = 8)))
      
      ggsave(file.path(out_dir, paste0(prefix, "_Composite_", index_name, ".pdf")), p_final, width = 22, height = 8)
      
      # Build Excel Data
      desc_stats <- df_clin %>% dplyr::group_by(Fat_Group) %>% dplyr::summarise(dplyr::across(dplyr::all_of(vars_list), list(Mean = ~mean(.x, na.rm=TRUE), SD = ~sd(.x, na.rm=TRUE)))) %>% tidyr::pivot_longer(cols = -Fat_Group) %>% tidyr::separate(name, into = c("Variable", "Stat"), sep = "_(?=[^_]+$)") %>% tidyr::pivot_wider(names_from = c(Fat_Group, Stat), values_from = value)
      combined_stats <- stats_lean %>% dplyr::filter(Variable %in% vars_list) %>% dplyr::mutate(Group = assign_clinical_group(Variable)) %>% dplyr::select(Variable, Group, Lean_Cor = Cor, Lean_P = P_Value) %>% dplyr::left_join(stats_obese %>% dplyr::filter(Variable %in% vars_list) %>% dplyr::select(Variable, Obese_Cor = Cor, Obese_P = P_Value), by="Variable") %>% dplyr::left_join(desc_stats, by="Variable")
      return(combined_stats)
    }
    
    m1_comp_excel[[index_name]] <<- generate_m1_panel(target_vars_comp, DIR_COMP, "Comprehensive")
    if(length(target_vars_cura) > 0) m1_cura_excel[[index_name]] <<- generate_m1_panel(target_vars_cura, DIR_CURA, "Curated")
  })
  
  # -------------------------------------------------------------------------
  # [MODULE 3] Systemic GSEA (Smart Line-Break Bubble Plot)
  # -------------------------------------------------------------------------
  message(">>> [MODULE 3] Executing GSEA Bubble Plot (Fixed Overlaps)...")
  local({
    run_gsea <- function(omics_df, clin_keys) {
      common <- intersect(omics_df$Subject_ID, clin_keys)
      if(length(common) < 10) return(NULL)
      df_o <- omics_df %>% dplyr::filter(Subject_ID %in% common) %>% dplyr::arrange(Subject_ID)
      df_c <- df_clin %>% dplyr::filter(Sample_Key %in% common) %>% dplyr::arrange(Sample_Key)
      
      # Clean numeric mapping for correlation
      mat_o <- df_o[, -1]
      cor_vals <- apply(mat_o, 2, function(x) if(sum(!is.na(x))<5) 0 else suppressWarnings(cor(x, df_c[[target_col]], method="spearman", use="pairwise")))
      gene_list <- sort(cor_vals, decreasing=TRUE)
      
      m_t2g <- msigdbr(species="Homo sapiens", category="H") %>% dplyr::select(gs_name, gene_symbol)
      tryCatch(GSEA(gene_list, TERM2GENE=m_t2g, pvalueCutoff=1, minGSSize=5, verbose=FALSE), error=function(e) NULL)
    }
    
    keys_obese <- df_clin$Sample_Key[df_clin$Fat_Group == "Obese"]
    keys_lean <- df_clin$Sample_Key[df_clin$Fat_Group == "Lean"]
    
    res_all <- list()
    runs <- list(
      list(name="Pre_Lean", omics=DATA_MUSCLE$Base, keys=keys_lean, tissue="Muscle"),
      list(name="Pre_Obese", omics=DATA_MUSCLE$Base, keys=keys_obese, tissue="Muscle"),
      list(name="Post3H_Lean", omics=DATA_MUSCLE$Delta, keys=keys_lean, tissue="Muscle"),
      list(name="Post3H_Obese", omics=DATA_MUSCLE$Delta, keys=keys_obese, tissue="Muscle"),
      list(name="Pre_Lean", omics=DATA_FAT$Base, keys=keys_lean, tissue="Adipose"),
      list(name="Pre_Obese", omics=DATA_FAT$Base, keys=keys_obese, tissue="Adipose"),
      list(name="Post3H_Lean", omics=DATA_FAT$Delta, keys=keys_lean, tissue="Adipose"),
      list(name="Post3H_Obese", omics=DATA_FAT$Delta, keys=keys_obese, tissue="Adipose")
    )
    
    for(r in runs) {
      if(!is.null(r$omics)) {
        g <- run_gsea(r$omics, r$keys)
        if(!is.null(g) && nrow(g@result) > 0) res_all[[paste(r$name, r$tissue, sep="_")]] <- g@result %>% dplyr::mutate(Stage_Fat = r$name, Tissue = r$tissue)
      }
    }
    
    df_gsea <- dplyr::bind_rows(res_all)
    if(nrow(df_gsea) > 0) {
      h_label <- paste0("H-", index_name)
      l_label <- paste0("L-", index_name)
      
      df_gsea <- df_gsea %>% dplyr::mutate(
        Timepoint = ifelse(grepl("Pre", Stage_Fat), "Pre", "Post3H"),
        FatGroup  = ifelse(grepl("Obese", Stage_Fat), "Obese", "Lean"),
        OC_Level  = ifelse(NES > 0, h_label, l_label),
        CleanName = stringr::str_to_title(gsub("_", " ", gsub("HALLMARK_", "", ID)))
      )
      
      m3_excel_list[[index_name]] <<- df_gsea
      
      core_paths <- c("HALLMARK_HEME_METABOLISM", "HALLMARK_OXIDATIVE_PHOSPHORYLATION", 
                      "HALLMARK_COAGULATION", "HALLMARK_UNFOLDED_PROTEIN_RESPONSE",
                      "HALLMARK_FATTY_ACID_METABOLISM", "HALLMARK_IL6_JAK_STAT3_SIGNALING")
      plot_df <- df_gsea %>% dplyr::filter(ID %in% core_paths)
      
      if(nrow(plot_df) > 0) {
        pathway_sig <- plot_df %>% dplyr::group_by(CleanName) %>% dplyr::summarise(TotSig = sum(-log10(p.adjust), na.rm=TRUE)) %>% dplyr::arrange(TotSig)
        plot_df$Tissue_Rank <- ifelse(plot_df$Tissue == "Adipose", 2, 1)
        plot_df <- plot_df %>% dplyr::left_join(pathway_sig, by="CleanName") %>% dplyr::arrange(TotSig, Tissue_Rank)
        plot_df$Pathway_Tissue <- factor(paste0(plot_df$CleanName, " (", plot_df$Tissue, ")"), levels = unique(paste0(plot_df$CleanName, " (", plot_df$Tissue, ")")))
        
        # New \n Spacing to resolve ggh4x
        lvls <- c(paste("Pre", "Lean", h_label, sep="\n"),  paste("Pre", "Lean", l_label, sep="\n"),
                  paste("Pre", "Obese", h_label, sep="\n"), paste("Pre", "Obese", l_label, sep="\n"),
                  paste("Post3H", "Lean", h_label, sep="\n"),  paste("Post3H", "Lean", l_label, sep="\n"),
                  paste("Post3H", "Obese", h_label, sep="\n"), paste("Post3H", "Obese", l_label, sep="\n"))
        plot_df$X_Nested <- factor(paste(plot_df$Timepoint, plot_df$FatGroup, plot_df$OC_Level, sep="\n"), levels = lvls)
        
        p_bub <- ggplot(plot_df, aes(x = X_Nested, y = Pathway_Tissue)) +
          geom_point(aes(size = -log10(p.adjust), fill = NES), shape = 21, color = "black") +
          scale_fill_gradient2(low = "#3C5488", mid = "white", high = "#E64B35", midpoint = 0) +
          scale_size(range = c(3, 10)) +
          scale_y_discrete(position = "right") +
          theme_bw(base_size = 13) +
          labs(title = paste(index_name, "Spatiotemporal GSEA"), x = "", y = "") +
          theme(
            panel.grid = element_blank(), panel.border = element_rect(color="black", fill=NA, linewidth=1),
            axis.text.x = element_text(color="black", size=11, face="plain", lineheight=0.9),
            axis.text.y.right = element_text(color="black", hjust=0, size=13, face="plain"),
            axis.ticks = element_line(color="black"), plot.title = element_text(hjust = 0.5, face = "bold", size=16)
          )
        # Save GSEA mostly to Curated folder as it's curated by default
        ggsave(file.path(DIR_CURA, paste0("GSEA_Spatiotemporal_Bubble_", index_name, ".pdf")), p_bub, width = 10, height = 6.5)
      }
    }
  })
}

# ==============================================================================
# --- 4. SAVE PUBLICATION-READY SUPTABLES ---
# ==============================================================================
message("\n>>> Generating Publication-Ready Supplementary Tables...")

if (!requireNamespace("openxlsx", quietly = TRUE)) install.packages("openxlsx")
library(openxlsx)

header_style <- createStyle(fontName = "Arial", fontSize = 11, fontColour = "white", fgFill = "#4F81BD", textDecoration = "bold")
sig_red      <- createStyle(fontColour = "#B2182B", textDecoration = "bold")
sig_blue     <- createStyle(fontColour = "#2166AC", textDecoration = "bold")

format_m1_excel <- function(data_list, out_path) {
  if(length(data_list) == 0) return()
  wb <- createWorkbook()
  for(idx in names(data_list)) {
    df <- data_list[[idx]] %>%
      dplyr::mutate(
        Lean_Sig = dplyr::case_when(Lean_P < 0.001 ~ "***", Lean_P < 0.01 ~ "**", Lean_P < 0.05 ~ "*", TRUE ~ "ns"),
        Obese_Sig = dplyr::case_when(Obese_P < 0.001 ~ "***", Obese_P < 0.01 ~ "**", Obese_P < 0.05 ~ "*", TRUE ~ "ns"),
        Sig_Tier = dplyr::case_when(Lean_P < 0.05 & Obese_P < 0.05 ~ 1, Lean_P < 0.05 | Obese_P < 0.05 ~ 2, TRUE ~ 3),
        Min_P = pmin(Lean_P, Obese_P, na.rm = TRUE)
      ) %>% dplyr::arrange(Sig_Tier, Min_P) %>% dplyr::select(-Sig_Tier, -Min_P) 
    
    addWorksheet(wb, idx); writeData(wb, idx, df)
    addStyle(wb, idx, style = header_style, rows = 1, cols = 1:ncol(df), gridExpand = TRUE)
    setColWidths(wb, idx, cols = 1:ncol(df), widths = "auto")
    
    col_l_cor <- match("Lean_Cor", names(df)); col_o_cor <- match("Obese_Cor", names(df))
    col_l_sig <- match("Lean_Sig", names(df)); col_o_sig <- match("Obese_Sig", names(df))
    
    conditionalFormatting(wb, idx, cols = col_l_cor, rows = 2:(nrow(df)+1), rule = ">0", style = sig_red)
    conditionalFormatting(wb, idx, cols = col_l_cor, rows = 2:(nrow(df)+1), rule = "<0", style = sig_blue)
    conditionalFormatting(wb, idx, cols = col_o_cor, rows = 2:(nrow(df)+1), rule = ">0", style = sig_red)
    conditionalFormatting(wb, idx, cols = col_o_cor, rows = 2:(nrow(df)+1), rule = "<0", style = sig_blue)
    conditionalFormatting(wb, idx, cols = col_l_sig, rows = 2:(nrow(df)+1), rule = "*", type = "contains", style = sig_red)
    conditionalFormatting(wb, idx, cols = col_o_sig, rows = 2:(nrow(df)+1), rule = "*", type = "contains", style = sig_red)
  }
  saveWorkbook(wb, out_path, overwrite = TRUE)
}

format_m1_excel(m1_comp_excel, file.path(DIR_OUT_ROOT, "Data_S11_Comprehensive_Clinical_Correlations.xlsx"))
format_m1_excel(m1_cura_excel, file.path(DIR_OUT_ROOT, "Data_S12_Curated_Clinical_Correlations.xlsx"))
message("   -> Saved M1 Comprehensive & Curated Tables.")

if(length(m3_excel_list) > 0) {
  wb_m3 <- createWorkbook()
  for(idx in names(m3_excel_list)) {
    df <- m3_excel_list[[idx]] %>% dplyr::mutate(Significance = dplyr::case_when(pvalue < 0.001 ~ "***", pvalue < 0.01 ~ "**", pvalue < 0.05 ~ "*", TRUE ~ "ns")) %>% dplyr::arrange(Tissue, Timepoint, pvalue)
    addWorksheet(wb_m3, idx); writeData(wb_m3, idx, df)
    addStyle(wb_m3, idx, style = header_style, rows = 1, cols = 1:ncol(df), gridExpand = TRUE)
    
    col_nes <- match("NES", names(df)); col_sig <- match("Significance", names(df))
    conditionalFormatting(wb_m3, idx, cols = col_nes, rows = 2:(nrow(df)+1), rule = ">0", style = sig_red)
    conditionalFormatting(wb_m3, idx, cols = col_nes, rows = 2:(nrow(df)+1), rule = "<0", style = sig_blue)
    conditionalFormatting(wb_m3, idx, cols = col_sig, rows = 2:(nrow(df)+1), rule = "*", type = "contains", style = sig_red)
  }
  saveWorkbook(wb_m3, file.path(DIR_OUT_ROOT, "Data_S13_Spatiotemporal_GSEA_Pathways.xlsx"), overwrite = TRUE)
  message("   -> Saved M3 GSEA Tables.")
}

message("\n=================================================================")
message(">>> FIG 6 CLINICAL INDICES PIPELINE COMPLETED!")
message(">>> Output: ", DIR_OUT_ROOT)
message("=================================================================")
